### ISSUE TITLE
Potential Bias in Dataset and Model

### ISSUE THREAD

**Issue by yunusserhat** [yeyimilk/LLMGeo#1]
Hi,

I noticed that both the dataset used for benchmarking (Google Street View) and the model with the best performance in the benchmark (Gemini) belong to Google. Could this impact the model's performance and bias?

Thanks

**Comment by yeyimilk** [comment]
Hi @yunusserhat you are right. We are not sure if Geimini had been trained on Google Street View data. We mentioned this concerned in the paper
